fix reference link
cisco-developer/api-insights pull request #45
Opened 2022-10-19 09:17 UTC by coliu19

The linter's doc link miss a -"ruleset", Here I fixed this missing part.

2022-10-20 17:44 UTC, npateriya requested changes
We want to point to a specific rule for example https://developer.cisco.com/docs/api-insights/#!rest-style/post not just top level page https://developer.cisco.com/docs/api-insights/#!rest-guidelines-ruleset.

Please refer https://developer.cisco.com/docs/api-insights/#!rest-guidelines-ruleset/rest-style-rules individual rule "Reference" for the exact location example

This applies to all refrences in rule-guidelines.json.

2022-10-20 17:44 UTC, npateriya commented on api/internal/data/rules-guidelines.json
> +    "mitigation": "Please update responses for the items identified. [Reference](https://developer.cisco.com/docs/api-insights/#!rest-guidelines-ruleset)",
We want to point to a specific rule for example https://developer.cisco.com/docs/api-insights/#!rest-style/post not just top level page. 

Please refer https://developer.cisco.com/docs/api-insights/#!rest-guidelines-ruleset/rest-style-rules individual rule "Reference" for the exact location example 

This applies to all refrences.

2022-10-21 08:57 UTC, coliu19 commented on api/internal/data/rules-guidelines.json
> +    "mitigation": "Please update responses for the items identified. [Reference](https://developer.cisco.com/docs/api-insights/#!rest-guidelines-ruleset)",
Updated most of them. There 15 rules that miss descriptions in all the docs. They are most about version and security. Examples are like oas2-path-based-versioning-major-only, oas2-https-only

2022-10-21 09:20 UTC, xinjixi reviewed
Hi @coliu19 , I checked the links, some links don't navigate to specific rule even when the anchor is given, should we create a PR to fix anchors in docs?

2022-10-21 09:20 UTC, xinjixi commented on api/internal/data/rules-completeness.json
> +    "mitigation": "Please add schema definitions for the items detected. [Reference](https://developer.cisco.com/docs/api-insights/#!documentation-completeness-ruleset/oas23-missing-schema-definition
This link doesn't navigate to specific rule, https://developer.cisco.com/docs/api-insights/#!documentation-completeness-ruleset/oas23-missing-schema-definition-missing-schema-definition

2022-10-21 09:20 UTC, xinjixi commented on api/internal/data/rules-completeness.json
> +    "mitigation": "Please add schema definitions for the items detected. [Reference](https://developer.cisco.com/docs/api-insights/#!documentation-completeness-ruleset/oas23-missing-schema-definition
This link doesn't navigate to specific rule as above

2022-10-21 09:20 UTC, xinjixi commented on api/internal/data/rules-completeness.json
> +    "title": "Some of the defined schema use object as a final field when describing their object structure. [Reference](https://developer.cisco.com/docs/api-insights/#!documentation-completeness-rul
This link doesn't navigate to specific rule as above.

2022-10-21 09:20 UTC, xinjixi commented on api/internal/data/rules-completeness.json
> +    "mitigation": "Please add a schema for the items detected. [Reference](https://developer.cisco.com/docs/api-insights/#!documentation-completeness-ruleset/oas2-3-missing-returned-representation-mi
This link doesn't navigate to specific rule as above.

2022-10-21 09:24 UTC, xinjixi commented on api/internal/data/rules-guidelines.json
> +    "mitigation": "Please update responses for the items identified. [Reference](https://developer.cisco.com/docs/api-insights/#!rest-guidelines-ruleset)",
Maybe we could add them in additional rules section of the docs and update the links as https://developer.cisco.com/docs/api-insights/#!rest-guidelines-ruleset/rest-additional-rules

2022-10-21 11:13 UTC, coliu19 commented on api/internal/data/rules-completeness.json
> +    "mitigation": "Please add schema definitions for the items detected. [Reference](https://developer.cisco.com/docs/api-insights/#!documentation-completeness-ruleset/oas23-missing-schema-definition
Yes, should have further fix there.

2022-11-02 16:02 UTC, merged